// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace UAFakeBrowser {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("UAFakeBrowerController")]
	public partial class UAFakeBrowerController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIWebView __mt__browser;
		
		private MonoTouch.UIKit.UITextField __mt__urlTextField;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_browser")]
		private MonoTouch.UIKit.UIWebView _browser {
			get {
				this.__mt__browser = ((MonoTouch.UIKit.UIWebView)(this.GetNativeField("_browser")));
				return this.__mt__browser;
			}
			set {
				this.__mt__browser = value;
				this.SetNativeField("_browser", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("_urlTextField")]
		private MonoTouch.UIKit.UITextField _urlTextField {
			get {
				this.__mt__urlTextField = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("_urlTextField")));
				return this.__mt__urlTextField;
			}
			set {
				this.__mt__urlTextField = value;
				this.SetNativeField("_urlTextField", value);
			}
		}
	}
}
